### ISSUE TITLE
Stats Blank

### ISSUE THREAD

**Issue by vegemike** [mrusse/Slsk-Upload-Stats-Tracker#12]
Hi, me again. Sorry, I know.
Genuinely not sure what's happening with this one:
The database files are completely intact, and when I try to submit data that's already there, it acts like expected.
![image_2024-05-30_174141081](https://github.com/mrusse/Slsk-Upload-Stats-Tracker/assets/116464261/ec3b5256-cdbf-4367-85af-4a50f0ecdd0f)
For whatever reason, the folders tab is fine (Actually, it might be a bit off but I'm not fully sure)
![image_2024-05-30_174742461](https://github.com/mrusse/Slsk-Upload-Stats-Tracker/assets/116464261/223d46bf-4b44-42e2-a3db-74fefe3b1036)

## All my paths are correct
The issue persists on restarting the application.
![image_2024-05-30_174253089](https://github.com/mrusse/Slsk-Upload-Stats-Tracker/assets/116464261/751a46a9-37f0-4be9-a899-46cce93b9bab)
I don't really have any other information to give but I can provide copies of the database if you'd like.
Sorry if this is the wrong place for this, seeing as its not quite the same nature as the other issues.

**Comment by mrusse** [comment]
If you send your database files I can have a look. Very strange indeed.

**Comment by vegemike** [comment]
Thanks for the quick reply.
[fileData.txt](https://github.com/mrusse/Slsk-Upload-Stats-Tracker/files/15503831/fileData.txt)
[parsedData.txt](https://github.com/mrusse/Slsk-Upload-Stats-Tracker/files/15503832/parsedData.txt)
[parsingData.txt](https://github.com/mrusse/Slsk-Upload-Stats-Tracker/files/15503833/parsingData.txt)
[userData.txt](https://github.com/mrusse/Slsk-Upload-Stats-Tracker/files/15503834/userData.txt)

**Comment by mrusse** [comment]
Thanks for sending those files. I just removed them from your comment for privacy. I was able to get it fixed, was a very weird issue but it ended up revealing some larger problems with the file stats page which is good. Should be a lot more robust now hopefully.

Give [v2.1.5](https://github.com/mrusse/Slsk-Upload-Stats-Tracker/releases/tag/v2.1.5) a try and let me know
